language: node_js

install:
   - npm install

before_script:
   - npm install -g casperjs
   - phantomjs --version; casperjs --version

before_deploy:
  - ./scripts/fetch.sh

deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_TOKEN
  app: $HEROKU_APP_NAME
  skip_cleanup: true
  on:
    branch: master
